#maila/custom_motors_interface:
#    ros__parameters:
# removed for composition node    
#(ref: https://github.com/ros2/rclcpp/issues/715  )

        topics:
            in_mode: "/autonomous_driver"
            in_manual_cmd: "/hw/manual_cmd"
            in_auto_cmd: "/hw/autonomous_cmd"
            in_emergency: "/hw/emergency_brake"
            out_cmd_info: "/hw/info"
            
        in_msg_max_period: 5000 # [milliseconds] if msg have period greater than this the car is forced to a neutral actuator position
        command_period: 20 # [milliseconds] time between each motors command sent
        out_msg_rate: 50 # [<command_period> callbacks] if =1 it sens each time it sends command to the motors 
        
        use_real_pca9685: true
        
        max_steering: 1.0 # [radians] can use minus sign to correct the steering direction
        steering_pwm:
            center: 0.0697
            dead_range: 0.0
            range: 0.016
            max_pwm: 4096

        max_throttle: 0.6 # full throttle of the car (set up 60% of the range for safety reason)
        throttle_pwm:
            center: 0.0748
            dead_range: 0.0015
            range: 0.025
            max_pwm: 4096
